

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  namespace: default
  labels:
    app: user-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
        - name: user-container
          image: us-east1-docker.pkg.dev/niveustraining/user-app/user-app:latest
          envFrom:
            - configMapRef:
                name: test-config


---


apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
  labels:
    app: user-app
spec:
  selector:
    app: user-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
